**If you lost points on the last checkpoint you can get them back by responding to TA/IA feedback**  

Update/change the relevant sections where you lost those points, make sure you respond on GitHub Issues to your TA/IA to call their attention to the changes you made here.

Please update your Timeline... no battle plan survives contact with the enemy, so make sure we understand how your plans have changed.

# COGS 108 - Data Checkpoint

# Names

- Lewis Aguilar
- Ana Caballero-Dips
- Nina Hong
- Yujie Kang
- Kathleen Ngo

# Research Question

-  Include a specific, clear data science question.
-  Make sure what you're measuring (variables) to answer the question is clear

What is your research question? Include the specific question you're setting out to answer. This question should be specific, answerable with data, and clear. A general question with specific subquestions is permitted. (1-2 sentences)

## Background and Prior Work


- Include a general introduction to your topic
- Include explanation of what work has been done previously
- Include citations or links to previous work

This section will present the background and context of your topic and question in a few paragraphs. Include a general introduction to your topic and then describe what information you currently know about the topic after doing your initial research. Include references to other projects who have asked similar questions or approached similar problems. Explain what others have learned in their projects.

Find some relevant prior work, and reference those sources, summarizing what each did and what they learned. Even if you think you have a totally novel question, find the most similar prior work that you can and discuss how it relates to your project.

References can be research publications, but they need not be. Blogs, GitHub repositories, company websites, etc., are all viable references if they are relevant to your project. It must be clear which information comes from which references. (2-3 paragraphs, including at least 2 references)

 **Use inline citation through HTML footnotes to specify which references support which statements** 

For example: After government genocide in the 20th century, real birds were replaced with surveillance drones designed to look just like birds.<a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1) Use a minimum of 2 or 3 citations, but we prefer more.<a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2) You need enough to fully explain and back up important facts. 

Note that if you click a footnote number in the paragraph above it will transport you to the proper entry in the footnotes list below.  And if you click the ^ in the footnote entry, it will return you to the place in the main text where the footnote is made.

To understand the HTML here, `<a name="#..."> </a>` is a tag that allows you produce a named reference for a given location.  Markdown has the construciton `[text with hyperlink](#named reference)` that will produce a clickable link that transports you the named reference.

1. <a name="cite_note-1"></a> [^](#cite_ref-1) Lorenz, T. (9 Dec 2021) Birds Aren’t Real, or Are They? Inside a Gen Z Conspiracy Theory. *The New York Times*. https://www.nytimes.com/2021/12/09/technology/birds-arent-real-gen-z-misinformation.html 
2. <a name="cite_note-2"></a> [^](#cite_ref-2) Also refs should be important to the background, not some randomly chosen vaguely related stuff. Include a web link if possible in refs as above.

# Hypothesis


- Include your team's hypothesis
- Ensure that this hypothesis is clear to readers
- Explain why you think this will be the outcome (what was your thinking?)

What is your main hypothesis/predictions about what the answer to your question is? Briefly explain your thinking. (2-3 sentences)

# Data

## Data overview

For each dataset include the following information
- Dataset #1
  - Dataset Name:
  - Link to the dataset:
  - Number of observations:
  - Number of variables:
- Dataset #2 (if you have more than one!)
  - Dataset Name:
  - Link to the dataset:
  - Number of observations:
  - Number of variables:
- etc

Now write 2 - 5 sentences describing each dataset here. Include a short description of the important variables in the dataset; what the metrics and datatypes are, what concepts they may be proxies for. Include information about how you would need to wrangle/clean/preprocess the dataset

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

Music-Major Data Set

In [1]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION 

##MAKE SURE TO INCLUDE HERE ANY OTHER IMPORTS YOU MIGHT NEED WE CAN NEED
import pandas as pd
import numpy as np

survey=pd.read_csv('cogs - 108 survey (Responses) - Form Responses 1.csv')

ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/ninahong/anaconda3/bin/python"
  * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/ninahong/anaconda3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libopenblas.0.dylib'
  Referenced from: '/Users/ninahong/anaconda3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so'
  Reason: tried: '/Users/ninahong/anaconda3/lib/python3.10/site-packages/numpy/core/../../../../libopenblas.0.dylib' (no such file), '/Users/ninahong/anaconda3/lib/python3.10/site-packages/numpy/core/../../../../libopenblas.0.dylib' (no such file), '/Users/ninahong/anaconda3/bin/../lib/libopenblas.0.dylib' (no such file), '/Users/ninahong/anaconda3/bin/../lib/libopenblas.0.dylib' (no such file), '/usr/local/lib/libopenblas.0.dylib' (no such file), '/usr/lib/libopenblas.0.dylib' (no such file)

In [ ]:
##DROP COLUMNS WE WILL NOT  USE
survey=survey.drop(['Timestamp'],axis=1)
survey=survey.drop(['What is/are your favorite color(s)? '],axis=1)
survey=survey.drop(["What are your hobbies? If it's more than one please put commas in between your responses. "],axis=1)

In [ ]:
##RENAME COLUMNS
survey = survey.rename(columns={'Age':'age',
                                'Gender':'gender',
                                'Hometown (include only state and city)': 'state_country', 
                                'favorite genre #1':'favorite_genre_1',
                                'favorite genre #2':'favorite_genre_2',
                                'favorite genre #3':'favorite_genre_3',
                                'Major/majors':'major_majors',
                                'Who is your favorite artist(s)?':'favorite_artist',
                                'How many hours per day do you listen to music? ': 'listening_hours',
                                'Do you play any instrument': 'instrument',
                                'What instrument do you play?': 'instrument_played',
                               'Are you an introvert or extrovert? ':'introvert_extrovert'})

In [2]:
##REMOVE LETTERS FROM AGE COLUMN
def standardize_age(str_age):

        if 'years old' in str_age:
            str_age = str_age.replace('years old', '')
            output = str_age
        else:
            output=str_age
        return output
    
survey['age']=survey['age'].apply(standardize_age)
survey['age']=survey['age'].astype(int)

NameError: name 'survey' is not defined

In [5]:
##MAKE VALUES IN COLUMNS TO LOWERCASE
survey['gender']=survey['gender'].str.lower()
survey['introvert_extrovert']=survey['introvert_extrovert'].str.lower()
survey['do you play an instrument?']=survey['do you play an instrument?'].str.lower()

In [6]:
##FAVORITE GENRE DATA CLEANING

def standardize_gen(str_gen):
    
        str_gen = str_gen.lower()
        str_gen = str_gen.strip()

        if '-' in str_gen:
            str_gen = str_gen.replace('-', '')
            output = str_gen
        if 'alternative rock' in str_gen or 'Alternative' in str_gen:
            str_gen = str_gen.replace('alternative rock', 'alternative')
            str_gen = str_gen.replace('Alternative', 'alternative')
            output = str_gen
        if 'oldies' in str_gen:
            str_gen = str_gen.replace('oldies', '')
            output = str_gen
        else:
            output=str_gen
        return output
    
survey['favorite_genre_1']=survey['favorite_genre_1'].apply(standardize_gen)
survey['favorite_genre_2']=survey['favorite_genre_2'].apply(standardize_gen)
survey['favorite_genre_3']=survey['favorite_genre_3'].apply(standardize_gen)

In [7]:
##CLEAN HOURS BY REMOVING SYMBOLS AND ADDING AVERAGES FOR PEOPLE WHO PROVIDED RANGE
def standardize_hours(str_hours):
    str_hours=str(str_hours)

    if 'less' in str_hours or '+' in str_hours or ' hour' in str_hours or ' hrs ' in str_hours or '~' in str_hours or '?' in str_hours:
        str_hours = str_hours.replace('less than ', '')
        str_hours = str_hours.replace('+', '')
        str_hours = str_hours.replace(' hours', '')
        str_hours = str_hours.replace(' hour', '')
        str_hours = str_hours.replace(' hrs ', '')
        str_hours = str_hours.replace('~', '')
        str_hours = str_hours.replace('?', '')
        output = str_hours       
    else:
        output = str_hours
    return output

survey['listening_hours']=survey['listening_hours'].apply(standardize_hours)

def standardize_avg(str_avg):
    str_avg=str(str_avg)
    if'0-1'in str_avg:
        output='0.5'
    elif '1-2' in str_avg:
        output='1.5'
    elif '2-3' in str_avg:
        output='2.5'
    elif '3-4' in str_avg:
        output= '3.5'
    elif '5-7' in str_avg:
        output= '6'
    elif ' ' in str_avg:
        str_avg=str_avg.replace('4 ','4')
        str_avg=str_avg.replace('3 ','3')
        output=str_avg
    elif '1/3' in str_avg:
        output=np.nan
    else:
        output=str_avg
    return output
survey['listening_hours']=survey['listening_hours'].apply(standardize_avg)
survey['listening_hours']=survey['listening_hours'].astype(float)

In [8]:
##ADD ' , ' TO SEPARATE THE MAJORS, SPLIT THE COLUMNS
survey['major_majors']=survey['major_majors'].replace('DSC & Business Econ','data science, business economics')
survey['major_majors']=survey['major_majors'].replace('Psychology & Human Developmental Science','psychology, human developmental science')
survey['major_majors']=survey['major_majors'].replace('Human Biology and Clinical Psychology','human biology, clinical psychology')
survey['major_majors']=survey['major_majors'].replace('CS and Math - Stats Double Major','computer science, mathematics')
survey['major_majors']=survey['major_majors'].replace('World Literature (Americas) and Sociology (Law and Society)','literature, sociology')
survey['major_majors']=survey['major_majors'].replace('Computer Science and Economics','computer science, economics')
survey['major_majors']=survey['major_majors'].replace('Psychology / Political Science','psychology, political science')
survey['major_majors']=survey['major_majors'].replace('Psychology & biochem ','psychology, biology')
   
survey[['major_1', 'major_2']] = survey['major_majors'].str.split(',', expand=True)
survey=survey.drop(['major_majors'],axis=1)

survey = survey.reindex(columns=['age', 'gender', 'state_country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])

In [9]:
##CLEANING DATA FOR MAJORS_1
survey['major_1']=survey['major_1'].str.lower()

def standardize_maj (str_maj):
    str_maj=str(str_maj)
    str_maj=str_maj.strip()

    if 'public' in str_maj:
        output='public health'
    elif 'cog' in str_maj:
        output='cognitive science'
    elif 'psyc' in str_maj:
        output='psychology'
    elif 'econ' in str_maj:
        output='economics'
    elif 'math' in str_maj:
        output='mathematics'
    elif 'bioengineering' in str_maj:
        output= 'bioengineering'
    elif 'biol' in str_maj:
        output= 'biology'
    elif 'int' in str_maj:
        output= 'international business'
    elif 'eng' in str_maj or 'cse' in str_maj:
        output= 'engineering'
    elif 'comp' in str_maj or 'cs' in str_maj:
        output= 'computer science'
    elif 'bioin' in str_maj or 'biochem' in str_maj:
        output='biology'
    elif 'esys' in str_maj:
        output='environmental systems'
    else:
        output=str_maj
    return output

survey['major_1']=survey['major_1'].apply(standardize_maj)

In [10]:
##CLEANING DATA FOR MAJOR_2
def standardize_major2 (str_maj2):
    str_maj2=str(str_maj2)
    str_maj2=str_maj2.lower()
    str_maj2=str_maj2.strip()
    if 'minor' in str_maj2 or 'none' in str_maj2 or 'machine' in str_maj2:
        output=np.nan
    elif 'econ' in str_maj2:
        output='economics'
    elif 'math' in str_maj2:
        output='mathematics'   
    elif 'bio' in str_maj2:
        output='biology'
    elif 'psyc' in str_maj2:
        output='psychology'
    else:
        output=str_maj2
    return output
survey['major_2']=survey['major_2'].apply(standardize_major2)

In [11]:
##FOR LOCATION USE STATE AND COUNTRY TO INCLUDE INTERNATIONAL STUDENTS
def standardize_loc(str_loc):
    str_loc=str(str_loc)
    str_loc=str_loc.strip()
    if ' CA' in str_loc or 'California' in str_loc or 'california' in str_loc or 'CA,' in str_loc or 'San francisco' in str_loc or 'CA ' in str_loc or 'south gate' in str_loc or 'akla' in str_loc or 'Sunny' in str_loc or 'San Diego' in str_loc:
        output='california, united states'
    elif ' Texas' in str_loc or 'TX' in str_loc:
        output='texas, united states'
    elif 'WA' in str_loc or 'Wa' in str_loc:
        output='washington, united states'
    elif 'MI' in str_loc:
        output='michigan, united states'
    elif 'PA' in str_loc:
        output='pennsylvania, united states' 
    elif 'NC' in str_loc:
        output='north carolina, united states' 
    elif 'NY' in str_loc:
        output='new york, united states'
    elif 'OR' in str_loc or 'Oregon' in str_loc:
        output='oregon, united states'
    elif 'Jersey' in str_loc:
        output='new jersey, united states'
    elif 'Ohio' in str_loc:
        output='ohio, united states'
    elif 'Illinois' in str_loc:
        output='illinois, united states'
    elif 'Kansas' in str_loc:
        output='kansas, united states'  
    elif 'Arizona' in str_loc:
        output='arizona, united states' 
    elif 'Monterrey' in str_loc:
        output='nuevo leon, mexico'
    elif 'spain' in str_loc:
        output='madrid, spain' 
    elif 'Jalisco' in str_loc:
        output='jalisco, mexico' 
    elif 'Sonora' in str_loc:
        output='sonora, mexico' 
    elif 'Belo' in str_loc:
        output='minas gerais, brazil'
    else:
        output=str_loc
    return output
survey['state_country']=survey['state_country'].replace('China',np.nan)
survey['state_country']=survey['state_country'].replace('International',np.nan)

In [12]:
##APPLY THE STANDARIZATION TO STATE AND COUNTRY, SEPARATE THEM INTO 2 COLUMNS
survey['state_country']=survey['state_country'].apply(standardize_loc)
survey['state_country']=survey['state_country'].replace('China',np.nan)
survey['state_country']=survey['state_country'].replace('International',np.nan)
survey['state_country']=survey['state_country'].str.lower()

survey[['state', 'country']] = survey['state_country'].str.split(',', expand=True)
survey=survey.drop(['state_country'],axis=1)

survey = survey.reindex(columns=['age', 'gender','state','country', 'major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])

In [13]:
##FOR OUR FIRST ANALYSIS WE WILL EXPLORE THE RELATION BETWEEN MUSIC AND MAJOR AND CONSIDER CONFOUNDING FACTORS PERTAINING TO PERSONAL FACTORS AND PREFERENCES

In [14]:
music_major_pref=survey.reindex(columns=['age', 'gender', 'state','country','introvert_extrovert','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3'])

In [15]:
music_major_pref.head()

,age,gender,state,country,introvert_extrovert,major_1,major_2,favorite_genre_1,favorite_genre_2,favorite_genre_3
0,21,female,california,united states,introvert,cognitive science,education sciences,pop,mandopop,r&b
1,19,male,texas,united states,extrovert,data science,NaN,r&b,jazz,pop
2,19,male,texas,united states,extrovert,data science,economics,classical,country,jazz
3,20,female,california,united states,introvert,bioengineering,mathematics,r&b,pop,folk
4,22,female,california,united states,introvert,psychology,NaN,christian,pop,hiphop/rap

Subset #1: Music orientation and major choice sub set

In [16]:
##ANOTHER WAY WE WILL EXPLORE THE DATA IS SEEING IF MUSIC ORIENTATION SUCH AS BEING PROFICIENT IN AN INSTRUMENT OR TIME SPENT LISTENING TO MUSICH CAN HAVE AN EFFECT ON MAJOR PREFERENCE

In [17]:
music_major_or=survey.reindex(columns=['listening_hours','do you play an instrument?','instrument_played','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3'])

In [18]:
##CHANGE INSTRUMENTS TO LOWERCASE AND CLEAN
def standardize_ins(str_ins):
    str_ins=str(str_ins)
    str_ins=str_ins.strip()
    str_ins=str_ins.lower()
    if 'erhu' in str_ins:
        str_ins=str_ins.replace('piano, erhu (chinese instrument)','piano, erhu')
        output=str_ins
    else:
        output=str_ins
    return output
music_major_or['instrument_played']=music_major_or['instrument_played'].apply(standardize_ins)

def standardize_com(str_com):
    str_com=str(str_com)
    str_com=str_com.strip()
    if ', ' in str_com:
        str_com=str_com.replace(', ',' ')
        output=str_com
    else:
        output=str_com
    return output
music_major_or['instrument_played']=music_major_or['instrument_played'].apply(standardize_com)

In [19]:
music_major_or.head()

,listening_hours,do you play an instrument?,instrument_played,major_1,major_2,favorite_genre_1,favorite_genre_2,favorite_genre_3
0,4.0,no,nan,cognitive science,education sciences,pop,mandopop,r&b
1,5.0,yes,clarinet,data science,NaN,r&b,jazz,pop
2,0.5,yes,guitar,data science,economics,classical,country,jazz
3,2.0,yes,piano,bioengineering,mathematics,r&b,pop,folk
4,3.0,yes,piano,psychology,NaN,christian,pop,hiphop/rap

Subset #2: Artist preference and major chice subset

In [26]:
#WE WILL USE THIS DATA SET TO SEE RELATION BETWEEN MUSIC ARTIST PREFERENCE AND MAJOR CHOICE

In [27]:
## ADD ' , ' TO BE ABLE TO SEPARATE ARTISTS INTO DIFFERNT COLUMNS 
survey['favorite_artist']=survey['favorite_artist'].replace('Kanye or Yung Lean','kanye, yung lean')
survey['favorite_artist']=survey['favorite_artist'].replace('Tyler, the Creator','tyler the creator')
survey['favorite_artist']=survey['favorite_artist'].replace('LE SSERAFIM 🧏\u200d♂️👆👉🙆\u200d♂️','le sserafim')


survey['favorite_artist']=survey['favorite_artist'].str.lower()
survey[['a1','a2','a3','a4','a5','a6','a7']] = survey['favorite_artist'].str.split(',', expand=True)

survey = survey.reindex(columns=['age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert','a1','a2','a3','a4','a5','a6','a7'])

In [28]:
##NEW DATAFRAME A1 FOR PEOPLE'S 1ST ARTIST LISTED
def standardize_a1 (str_a1):
    str_a1=str(str_a1)
    str_a1=str_a1.lower()
    str_a1=str_a1.strip()
    if 'specific' in str_a1 or 'none' in str_a1 or 'nan' in str_a1:
        output=np.nan
    else:
        output=str_a1
    return output
survey['a1']=survey['a1'].apply(standardize_a1)
survey_a1=survey.reindex(columns=['a1','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])
survey_a1=survey_a1.dropna(subset='a1')
survey_a1 = survey_a1.rename(columns={'a1':'artist_name'})

In [29]:
##NEW DATAFRAME A2 FOR PEOPLE'S 2ND ARTIST LISTED
def standardize_a2 (str_a2):
    str_a2=str(str_a2)
    str_a2=str_a2.lower()
    str_a2=str_a2.strip()
    if 'none' in str_a2 or 'nan' in str_a2:
        output=np.nan
    else:
        output=str_a2
    return output
survey['a2']=survey['a2'].apply(standardize_a2)
survey_a2=survey.reindex(columns=['a2','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])
survey_a2=survey_a2.dropna(subset='a2')
survey_a2 = survey_a2.rename(columns={'a2':'artist_name'})

In [30]:
##NEW DATAFRAME A3 FOR PEOPLE'S 3RD ARTIST LISTED
def standardize_a3 (str_a3):
    str_a3=str(str_a3)
    str_a3=str_a3.lower()
    str_a3=str_a3.strip()
    if 'none' in str_a3 or 'nan' in str_a3:
        output=np.nan
    elif 'é' in str_a3:
        output='beyonce'
    else:
        output=str_a3
    return output
survey['a3']=survey['a3'].apply(standardize_a3)
survey_a3=survey.reindex(columns=['a3','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])
survey_a3=survey_a3.dropna(subset='a3')
survey_a3 = survey_a3.rename(columns={'a3':'artist_name'})

In [31]:
##NEW DATAFRAME A4 FOR PEOPLE'S 4TH ARTIST LISTED
def standardize_a4 (str_a4):
    str_a4=str(str_a4)
    str_a4=str_a4.lower()
    str_a4=str_a4.strip()
    if 'ray' in str_a4:
        output='lana del rey'
    elif 'wising' in str_a4:
        output='wisin y yandel'
    elif 'none' in str_a4 or 'nan' in str_a4:
        output=np.nan
    else:
        output=str_a4
    return output
survey['a4']=survey['a4'].apply(standardize_a4)
survey_a4=survey.reindex(columns=['a4','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])
survey_a4=survey_a4.dropna(subset='a4')
survey_a4 = survey_a4.rename(columns={'a4':'artist_name'})

In [32]:
##NEW DATAFRAME A5 FOR PEOPLE'S 5TH ARTIST LISTED
def standardize_a5 (str_a5):
    str_a5=str(str_a5)
    str_a5=str_a5.lower()
    str_a5=str_a5.strip()
    if 'none' in str_a5 or 'nan' in str_a5:
        output=np.nan
    else:
        output=str_a5
    return output
survey['a5']=survey['a5'].apply(standardize_a5)
survey_a5=survey.reindex(columns=['a5','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])
survey_a5=survey_a5.dropna(subset='a5')
survey_a5 = survey_a5.rename(columns={'a5':'artist_name'})

In [33]:
##NEW DATAFRAME A6 FOR PEOPLE'S 6TH ARTIST LISTED
survey_a6=survey.reindex(columns=['a6','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])
survey_a6=survey_a6.dropna(subset='a6')
survey_a6 = survey_a6.rename(columns={'a6':'artist_name'})

In [34]:
##NEW DATAFRAME A6 FOR PEOPLE'S 7TH ARTIST LISTED
survey_a7=survey.reindex(columns=['a7','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','do you play an instrument?','instrument_played','introvert_extrovert'])
survey_a7=survey_a7.dropna(subset='a7')
survey_a7 = survey_a7.rename(columns={'a7':'artist_name'})

In [35]:
##PUTTING THE DATAFRAMES TOGETHER

In [36]:
favorite_artist = pd.concat([survey_a1, survey_a2, survey_a3, survey_a4, survey_a5, survey_a6, survey_a7], ignore_index=True, axis=0)
favorite_artist = favorite_artist.reindex(columns=['artist_name','age','gender','major_1','major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','introvert_extrovert'])
favorite_artist.head()

,artist_name,age,gender,major_1,major_2,favorite_genre_1,favorite_genre_2,favorite_genre_3,introvert_extrovert
0,jonah kagen,21,female,cognitive science,education sciences,pop,mandopop,r&b,introvert
1,laufey,19,male,data science,NaN,r&b,jazz,pop,extrovert
2,laufey,20,female,bioengineering,mathematics,r&b,pop,folk,introvert
3,phil wickham,22,female,psychology,NaN,christian,pop,hiphop/rap,introvert
4,frank ocean,20,female,media,NaN,pop,folk,hiphop/rap,introvert

In [37]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

# Ethics & Privacy

- Thoughtful discussion of ethical concerns included
- Ethical concerns consider the whole data science process (question asked, data collected, data being used, the bias in data, analysis, post-analysis, etc.)
- How your group handled bias/ethical concerns clearly described

Acknowledge and address any ethics & privacy related issues of your question(s), proposed dataset(s), and/or analyses. Use the information provided in lecture to guide your group discussion and thinking. If you need further guidance, check out [Deon's Ethics Checklist](http://deon.drivendata.org/#data-science-ethics-checklist). In particular:

- Are there any biases/privacy/terms of use issues with the data you propsed?
- Are there potential biases in your dataset(s), in terms of who it composes, and how it was collected, that may be problematic in terms of it allowing for equitable analysis? (For example, does your data exclude particular populations, or is it likely to reflect particular human biases in a way that could be a problem?)
- How will you set out to detect these specific biases before, during, and after/when communicating your analysis?
- Are there any other issues related to your topic area, data, and/or analyses that are potentially problematic in terms of data privacy and equitable impact?
- How will you handle issues you identified?

# Team Expectations


Read over the [COGS108 Team Policies](https://github.com/COGS108/Projects/blob/master/COGS108_TeamPolicies.md) individually. Then, include your group’s expectations of one another for successful completion of your COGS108 project below. Discuss and agree on what all of your expectations are. Discuss how your team will communicate throughout the quarter and consider how you will communicate respectfully should conflicts arise. By including each member’s name above and by adding their name to the submission, you are indicating that you have read the COGS108 Team Policies, accept your team’s expectations below, and have every intention to fulfill them. These expectations are for your team’s use and benefit — they won’t be graded for their details.

* *Team Expectation 1*
* *Team Expectation 2*
* *Team Expecation 3*
* ...

# Project Timeline Proposal


| Meeting Date | Meeting Time | Completed Before Meeting | Discuss at Meeting |
|---|---|---|---|
| 2/07 |  8 PM | N/A | Brainstorm ideas for hypothesis/research question; Section Distributions for Proposal | 
| 2/12 |  7 PM | Submit Project Proposal; Start background research on the topic and hypothesis | Discuss Team Expectations; Section Distributions for the Final Project; Work on the Google Form | 
| 2/16 | 8 AM  | Rough Draft of the Google Form  | Finalize hypothesis/research question; Finalize Google form |
| 2/19 | 7 PM  | Search for other datasets; Release Google Form | Discuss Checkpoint #1: Data; Work on Checkpoint #1; Release of Google Form |
| 2/23 | 8 AM  | Do more research into the topic; Get familiar with the data collected; Rough Draft of Checkpoint #1 | Check-in on progress; Discuss Checkpoint #1, Look for other  datasets |
| 2/26 | 7 PM  | Submit Checkpoint #1 [due 02/25]| Discuss data gathered by Google Form; Discuss Checkpoint #2; Discuss Final Report; Work on Data Section together |
| 3/01 | 8 AM  | Get familiar with data gathered so far | Check-in on progress; Discuss Checkpoint #2 |
| 3/04 | 7 PM  | Finish gathering dataset | Organize data; Discuss Checkpoint #2; Discuss Final Report|
| 3/08 | 8 AM  | Rough Draft of Checkpoint #2 | Check-in on progress |
| 3/11 | 7 PM  | Submit Checkpoint #2 [due 02/10]; Understand expectations of what’s needed for Final Report and Final Video | Discuss progress on the Final Report and Final Video; Outline the Final Report |
| 3/15 | 8 AM  | Rough Draft of Final Report | Check-in on progress; Discuss rough draft of Final Report, Discuss Final Video |
| 3/16-17 | [Not a meeting] | NA | Record Final Video |
| 3/18 | 7 PM (Subject to change due to Finals)  | Finalize Final Report and Final Video | Discuss finalized Final Report and Final Video |
| 3/19-20 | [Not a meeting] | NA | Record Final Video |
| 3/20 | Before 11:59 PM [Not a meeting] | NA | Submit the Final Report and Final Video |