**If you lost points on the last checkpoint you can get them back by responding to TA/IA feedback**  

Update/change the relevant sections where you lost those points, make sure you respond on GitHub Issues to your TA/IA to call their attention to the changes you made here.

Please update your Timeline... no battle plan survives contact with the enemy, so make sure we understand how your plans have changed.

# COGS 108 - Data Checkpoint

# Names

- Lewis Aguilar
- Ana Caballero-Dips
- Nina Hong
- Yujie Kang
- Kathleen Ngo

# Research Question

How does music preference correlate with college major choice among UCSD students, and can this correlation be reflected in the popularity of music artists among different majors? What is the relationship between students' music taste, measured by their preferred artists or genres, and their chosen field of study, with a focus on identifying any patterns or trends in music preference across various majors?

## Background and Prior Work

Choosing a major is one of the most important decisions college students make. This choice impacts their future careers and their development as a person. There are many factors that one considers when taking into account what they want to study such as high school classes interests, what their family members studied, and many more. For our project we want to investigate if there are any subconscious influences when choosing a major. To do so, we want to see if there is a correlation between a student's music taste and major election. 

A study pertaining to music taste and personality showed that people with certain personality traits tend to enjoy certain music genres more than others <a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1). This study showed that music is somehow embedded in certain personality traits of people. Similarly, other studies found out that personality traits do play a role when choosing a college major <a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2). Both of these studies are making reference to the “Big Five Personality Traits”. By seeing that personality is related to both music and major choice, we want to discover the relationship between both or if it is solely the personality and music taste that is not really reflected among majors.

The relationship between music taste and other life aspects has been studied before as well. For instance, a study looked at the relationship between music taste and job choice and they found there was a relation between both <a name="cite_ref-3"></a>[<sup>3</sup>](#cite_note-3). There has been previous research on topics where music taste is used to evaluate people’s decision making. This research study is important because it shows that music can be related to people’s life and career so based on this we want to explore how music plays a role before choosing a job. 

The research conducted introduced some critical points that bring to light how music choice can play a role in influencing an individual's personality. While they all highlight the connection between music preferences and various aspects of an individual's life, the relationship is not yet fully understood as the study did not take into consideraion of multiple factors of an individual's background within their particulsr studies such as their background. 

This gap in understanding presents an opportunity for further exploration into how music taste could be a significant, yet subconscious, influence on a student's selection of a college major. To better address this we plan on diversifying our sample pool to be more representative of the population of students at UC San Diego and within our data collection method we plan on repurposing some of the strategies implemented by the Humburg study to understand how we can structure our questionnaire to collect data regarding the effect of the big five personality traits. By refining our methodology and broadening our sample, we aim to uncover how music preferences may guide the academic and professional paths students choose, providing deeper insights into the intersection between personality, music taste, and educational decisions. 

<a name="cite_note-1"></a> [1.](#cite_ref-1) Nave, G. et. al. (2018). Musical Preferences Predict Personality: Evidence From Active Listening and Facebook Likes. Psychological science, 29(7), 1145–1158. https://doi.org/10.1177/0956797618761659 

<a name="cite_note-2"></a> [2.](#cite_ref-2) Humburg, M. (2012). The Effect of the Big Five Personality Traits on College Major Choice : Evidence from a Dutch longitudinal youth cohort study. The Society of Labor Economists, 1-20. https://www.sole-jole.org/assets/docs/13190.pdf

<a name='cite_note-3'></a> [3.](#cite_ref-3) Kno, D. (2016). What your job reveals about the music you listen to, indy100.https://www.indy100.com/news/what-your-job-reveals-about-the-music-you-listen-to-7427961

# Hypothesis

We predict that there will be a correlation between music preference and college major choice among UCSD students. Building on previous research indicating connections between personality traits and both music preference and major selection, we hypothesize that certain music genres may resonate more with the personality traits associated with specific majors. Therefore, we expect to observe a pattern where certain music artists or genres are more popular among students majoring in particular fields, reflecting underlying personality traits influencing both music preference and major choice.

# Data

## Data overview

We are going to use the dataset "Music Interests" in https://github.com/COGS108/Group041_WI24/blob/master/cogs%20-%20108%20survey%20(Responses)%20-%20Form%20Responses%201.csv. This dataset has 102 observations and 15 variables. We collected this data from UCSD students and asked about their major, age, music preference, artist preference, and some other aspects in order to analyze them in multiple aspects.

**Music-Major Data Set**

We want to show the responses receive from UCSD students by showing the first five forms being collected anonymously.

In [35]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION 

##MAKE SURE TO INCLUDE HERE ANY OTHER IMPORTS YOU MIGHT NEED WE CAN NEED
import pandas as pd
import numpy as np

survey=pd.read_csv('cogs - 108 survey (Responses) - Form Responses 1.csv')

# Take a look at the first few rows of the dataset
survey.head()

,Timestamp,Age,Gender,Hometown (include only state and city),Major/majors,favorite genre #1,favorite genre #2,favorite genre #3,Who is your favorite artist(s)?,How many hours per day do you listen to music?,Do you play any instrument,What instrument do you play?,Are you an introvert or extrovert?,What are your hobbies? If it's more than one please put commas in between your responses.,What is/are your favorite color(s)?
0,2/13/2024 13:21:59,21,Female,"Sunnyvale, CA","Cognitive Science (D&I), Education Sciences",pop,mandopop,R&B,"Jonah Kagen, Chen, Eric Chou",4,No,NaN,Introvert,"rock climbing, dancing, singing, aerial arts, ...",Green
1,2/13/2024 13:22:12,19,Male,"Dallas, Texas",Data Science,R&B,jazz,pop,Laufey,5,Yes,clarinet,Extrovert,"Reading, Zelda games",Green
2,2/13/2024 13:23:01,19,Male,Dallas Texas,DSC & Business Econ,classical,country,jazz,NaN,0-1,Yes,guitar,Extrovert,"Table tennis, read, video games",Yellow
3,2/13/2024 13:24:14,20,Female,"Garden Grove, CA","Bioengineering, Math/CS",R&B,pop,folk,"Laufey, NIKI, Renee Rap",2,Yes,piano,Introvert,"Knitting, Drawing","Red, Pink, Brown, Green, Black"
4,2/13/2024 13:27:11,22,Female,"Brea, California",Business Psychology,Christian,pop,hiphop/rap,Phil Wickham,3,Yes,piano,Introvert,"baking, cooking, music, cafe hopping, traveling",Purple

Although we collected a variety of responses pertaining to many topics, we will remove timestamp column as it is not necessary for this survey and their favorite colors and hobbies as they do not directly contribute to the  relationship between music taste and majors being chosen by UCSD students.

In [36]:
##DROP COLUMNS WE WILL NOT  USE
survey=survey.drop(['Timestamp'],axis=1)
survey=survey.drop(['What is/are your favorite color(s)? '],axis=1)
survey=survey.drop(["What are your hobbies? If it's more than one please put commas in between your responses. "],axis=1)

In [37]:
##RENAME COLUMNS TO MAKE THEM EASIER TO WORK WITH
survey = survey.rename(columns={'Age':'age',
                                'Gender':'gender',
                                'Hometown (include only state and city)': 'state_country', 
                                'favorite genre #1':'favorite_genre_1',
                                'favorite genre #2':'favorite_genre_2',
                                'favorite genre #3':'favorite_genre_3',
                                'Major/majors':'major_majors',
                                'Who is your favorite artist(s)?':'favorite_artist',
                                'How many hours per day do you listen to music? ': 'listening_hours',
                                'Do you play any instrument': 'whether_instrument',
                                'What instrument do you play?': 'instrument_played',
                               'Are you an introvert or extrovert? ':'introvert_extrovert'})

After renaming the columns with readable categories, the table below displays a sample of the information we want to focus on and utilize for our findings.

In [38]:
survey.head()

,age,gender,state_country,major_majors,favorite_genre_1,favorite_genre_2,favorite_genre_3,favorite_artist,listening_hours,whether_instrument,instrument_played,introvert_extrovert
0,21,Female,"Sunnyvale, CA","Cognitive Science (D&I), Education Sciences",pop,mandopop,R&B,"Jonah Kagen, Chen, Eric Chou",4,No,NaN,Introvert
1,19,Male,"Dallas, Texas",Data Science,R&B,jazz,pop,Laufey,5,Yes,clarinet,Extrovert
2,19,Male,Dallas Texas,DSC & Business Econ,classical,country,jazz,NaN,0-1,Yes,guitar,Extrovert
3,20,Female,"Garden Grove, CA","Bioengineering, Math/CS",R&B,pop,folk,"Laufey, NIKI, Renee Rap",2,Yes,piano,Introvert
4,22,Female,"Brea, California",Business Psychology,Christian,pop,hiphop/rap,Phil Wickham,3,Yes,piano,Introvert

The standardize_age function takes a string input representing an age value and standardizes it by removing any text ('years old' or 'years') and returning the age as an integer. This code ensures that the 'age' column in the 'survey' DataFrame is cleaned and standardized, making it ready for further analysis or visualization.

In [39]:
##MAKE THE AGE COLUMN AN INTEGER
def standardize_age(str_age):

        if 'years old' in str_age:
            str_age = str_age.replace('years old', '')
            output = str_age
        elif 'years' in str_age:
            str_age = str_age.replace('years', '')
            output = str_age
        else:
            output=str_age
        return int(output)
    
survey['age']=survey['age'].apply(standardize_age)
survey['age']=survey['age'].astype(int)

Let's convert the values in specific columns of the 'survey' DataFrame to lowercase.

In [40]:
##MAKE VALUES IN COLUMNS TO LOWERCASE
survey['gender']=survey['gender'].str.lower()
survey['introvert_extrovert']=survey['introvert_extrovert'].str.lower()
survey['whether_instrument']=survey['whether_instrument'].str.lower()

We want to ensure consistency and clarity in the representation of students' favorite music genres in this survey dataset. We want to convert all genre labels to lowercase and standardizing certain genre names.

Sometimes, the names may contain hypgens or other marks and we should remove them to treat genres as single entities. This standardization process simplifies the data, ensuring that similar genres are grouped together consistently for analysis.

In [41]:
##FAVORITE GENRE DATA CLEANING
survey['favorite_genre_1']=survey['favorite_genre_1'].str.lower()
survey['favorite_genre_2']=survey['favorite_genre_2'].str.lower()
survey['favorite_genre_3']=survey['favorite_genre_3'].str.lower()

def standardize_gen(str_gen):
    
        str_gen = str_gen.strip()

        if '-' in str_gen:
            str_gen = str_gen.replace('-', '')
            output = str_gen
        if 'alternative rock' in str_gen or 'Alternative' in str_gen:
            str_gen = str_gen.replace('alternative rock', 'alternative')
            str_gen = str_gen.replace('Alternative', 'alternative')
            output = str_gen
        if 'oldies' in str_gen:
            str_gen = str_gen.replace('oldies', '')
            output = str_gen
        else:
            output=str_gen
        return output
    
survey['favorite_genre_1']=survey['favorite_genre_1'].apply(standardize_gen)
survey['favorite_genre_2']=survey['favorite_genre_2'].apply(standardize_gen)
survey['favorite_genre_3']=survey['favorite_genre_3'].apply(standardize_gen)

There seems to be more symbols and phrases such as 'less than', '+', '~', and '?', as well as variations of 'hour(s)', so let's ensure uniform formatting of the hour values. Also, we need to assign midpoints for specified ranges that cannot be decided as a single value.

In [42]:
##CLEAN HOURS BY REMOVING SYMBOLS AND ADDING AVERAGES FOR PEOPLE WHO PROVIDED RANGE
def standardize_hours(str_hours):
    str_hours=str(str_hours)

    if 'less' in str_hours or '+' in str_hours or ' hour' in str_hours or ' hrs ' in str_hours or '~' in str_hours or '?' in str_hours:
        str_hours = str_hours.replace('less than ', '')
        str_hours = str_hours.replace('+', '')
        str_hours = str_hours.replace(' hours', '')
        str_hours = str_hours.replace(' hour', '')
        str_hours = str_hours.replace(' hrs ', '')
        str_hours = str_hours.replace('~', '')
        str_hours = str_hours.replace('?', '')
        output = str_hours       
    else:
        output = str_hours
    return output

survey['listening_hours']=survey['listening_hours'].apply(standardize_hours)

def standardize_avg(str_avg):
    str_avg=str(str_avg)
    if'0-1'in str_avg:
        output='0.5'
    elif '1-2' in str_avg:
        output='1.5'
    elif '2-3' in str_avg:
        output='2.5'
    elif '3-4' in str_avg:
        output= '3.5'
    elif '5-7' in str_avg:
        output= '6'
    elif ' ' in str_avg:
        str_avg=str_avg.replace('4 ','4')
        str_avg=str_avg.replace('3 ','3')
        output=str_avg
    elif '1/3' in str_avg:
        output=np.nan
    else:
        output=str_avg
    return output
survey['listening_hours']=survey['listening_hours'].apply(standardize_avg)
survey['listening_hours']=survey['listening_hours'].astype(float)

Next, we refactor the structure of the 'survey' DataFrame by replacing combined major names with comma-separated representations and then splitting them into two separate columns 'major_1' and 'major_2'. Splitting and reordering method are then followed for better organization and analysis of major data, facilitating easier examination of correlations between majors and other variables with enhanced readability.

In [43]:
##ADD ' , ' TO SEPARATE THE MAJORS, SPLIT THE COLUMNS
survey['major_majors']=survey['major_majors'].replace('DSC & Business Econ','data science, business economics')
survey['major_majors']=survey['major_majors'].replace('Psychology & Human Developmental Science','psychology, human developmental science')
survey['major_majors']=survey['major_majors'].replace('Human Biology and Clinical Psychology','human biology, clinical psychology')
survey['major_majors']=survey['major_majors'].replace('CS and Math - Stats Double Major','computer science, mathematics')
survey['major_majors']=survey['major_majors'].replace('World Literature (Americas) and Sociology (Law and Society)','literature, sociology')
survey['major_majors']=survey['major_majors'].replace('Computer Science and Economics','computer science, economics')
survey['major_majors']=survey['major_majors'].replace('Psychology / Political Science','psychology, political science')
survey['major_majors']=survey['major_majors'].replace('Psychology & biochem ','psychology, biology')
   
survey[['major_1', 'major_2']] = survey['major_majors'].str.split(',', expand=True)
survey=survey.drop(['major_majors'],axis=1)

survey = survey.reindex(columns=['age', 'gender', 'state_country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])

In [44]:
##CLEANING DATA FOR MAJORS_1
survey['major_1']=survey['major_1'].str.lower()

def standardize_maj (str_maj):
    str_maj=str(str_maj)
    str_maj=str_maj.strip()

    if 'public' in str_maj:
        output='public health'
    elif 'cog' in str_maj:
        output='cognitive science'
    elif 'psyc' in str_maj:
        output='psychology'
    elif 'econ' in str_maj:
        output='economics'
    elif 'math' in str_maj:
        output='mathematics'
    elif 'bioengineering' in str_maj:
        output= 'bioengineering'
    elif 'biol' in str_maj:
        output= 'biology'
    elif 'int' in str_maj:
        output= 'international business'
    elif 'eng' in str_maj or 'cse' in str_maj:
        output= 'engineering'
    elif 'comp' in str_maj or 'cs' in str_maj:
        output= 'computer science'
    elif 'bioin' in str_maj or 'biochem' in str_maj:
        output='biology'
    elif 'esys' in str_maj:
        output='environmental systems'
    else:
        output=str_maj
    return output

survey['major_1']=survey['major_1'].apply(standardize_maj)

In [45]:
##CLEANING DATA FOR MAJOR_2
def standardize_major2 (str_maj2):
    str_maj2=str(str_maj2)
    str_maj2=str_maj2.lower()
    str_maj2=str_maj2.strip()
    if 'minor' in str_maj2 or 'none' in str_maj2 or 'machine' in str_maj2:
        output=np.nan
    elif 'econ' in str_maj2:
        output='economics'
    elif 'math' in str_maj2:
        output='mathematics'   
    elif 'bio' in str_maj2:
        output='biology'
    elif 'psyc' in str_maj2:
        output='psychology'
    else:
        output=str_maj2
    return output
survey['major_2']=survey['major_2'].apply(standardize_major2)

For the next column, we need to clean and standardize location data, making it uniform and suitable for analysis, such as examining geographic trends among survey respondents.

In [46]:
##FOR LOCATION USE STATE AND COUNTRY TO INCLUDE INTERNATIONAL STUDENTS
def standardize_loc(str_loc):
    str_loc=str(str_loc)
    str_loc=str_loc.strip()
    if ' CA' in str_loc or 'California' in str_loc or 'california' in str_loc or 'CA,' in str_loc or 'San francisco' in str_loc or 'CA ' in str_loc or 'south gate' in str_loc or 'akla' in str_loc or 'Sunny' in str_loc or 'San Diego' in str_loc:
        output='california, united states'
    elif ' Texas' in str_loc or 'TX' in str_loc:
        output='texas, united states'
    elif 'WA' in str_loc or 'Wa' in str_loc:
        output='washington, united states'
    elif 'MI' in str_loc:
        output='michigan, united states'
    elif 'PA' in str_loc:
        output='pennsylvania, united states' 
    elif 'NC' in str_loc:
        output='north carolina, united states' 
    elif 'NY' in str_loc:
        output='new york, united states'
    elif 'OR' in str_loc or 'Oregon' in str_loc:
        output='oregon, united states'
    elif 'Jersey' in str_loc:
        output='new jersey, united states'
    elif 'Ohio' in str_loc:
        output='ohio, united states'
    elif 'Illinois' in str_loc:
        output='illinois, united states'
    elif 'Kansas' in str_loc:
        output='kansas, united states'  
    elif 'Arizona' in str_loc:
        output='arizona, united states' 
    elif 'Monterrey' in str_loc:
        output='nuevo leon, mexico'
    elif 'spain' in str_loc:
        output='madrid, spain' 
    elif 'Jalisco' in str_loc:
        output='jalisco, mexico' 
    elif 'Sonora' in str_loc:
        output='sonora, mexico' 
    elif 'Belo' in str_loc:
        output='minas gerais, brazil'
    else:
        output=str_loc
    return output
survey['state_country']=survey['state_country'].replace('China',np.nan)
survey['state_country']=survey['state_country'].replace('International',np.nan)

Splitting up state and country into two distinct columns allow for deeper analysis.

In [47]:
##APPLY THE STANDARIZATION TO STATE AND COUNTRY, SEPARATE THEM INTO 2 COLUMNS
survey['state_country']=survey['state_country'].apply(standardize_loc)
survey['state_country']=survey['state_country'].replace('China',np.nan)
survey['state_country']=survey['state_country'].replace('International',np.nan)
survey['state_country']=survey['state_country'].str.lower()

survey[['state', 'country']] = survey['state_country'].str.split(',', expand=True)
survey=survey.drop(['state_country'],axis=1)

survey = survey.reindex(columns=['age', 'gender','state','country', 'major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])

For our first analysis we will explore the relation between music and major and consider confounding factors pertaining to personal factors and preferences.

In [48]:
music_major_pref=survey.reindex(columns=['age', 'gender', 'state','country','introvert_extrovert','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3'])

In [49]:
music_major_pref.head()

,age,gender,state,country,introvert_extrovert,major_1,major_2,favorite_genre_1,favorite_genre_2,favorite_genre_3
0,21,female,california,united states,introvert,cognitive science,education sciences,pop,mandopop,r&b
1,19,male,texas,united states,extrovert,data science,NaN,r&b,jazz,pop
2,19,male,texas,united states,extrovert,data science,economics,classical,country,jazz
3,20,female,california,united states,introvert,bioengineering,mathematics,r&b,pop,folk
4,22,female,california,united states,introvert,psychology,NaN,christian,pop,hiphop/rap

**Subset #1: Music orientation and major choice sub set**

Another way we will explore the data is seeing if music orientation such as being proficient in an instrument or time spent listening to musich can have an effect on major preference.

In [50]:
music_major_or=survey.reindex(columns=['listening_hours','whether_instrument','instrument_played','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3'])

In [51]:
##CHANGE INSTRUMENTS TO LOWERCASE AND CLEAN
def standardize_ins(str_ins):
    str_ins=str(str_ins)
    str_ins=str_ins.strip()
    str_ins=str_ins.lower()
    if 'erhu' in str_ins:
        str_ins=str_ins.replace('piano, erhu (chinese instrument)','piano, erhu')
        output=str_ins
    else:
        output=str_ins
    return output
music_major_or['instrument_played']=music_major_or['instrument_played'].apply(standardize_ins)

def standardize_com(str_com):
    str_com=str(str_com)
    str_com=str_com.strip()
    if ', ' in str_com:
        str_com=str_com.replace(', ',' ')
        output=str_com
    else:
        output=str_com
    return output
music_major_or['instrument_played']=music_major_or['instrument_played'].apply(standardize_com)

In [52]:
music_major_or.head()

,listening_hours,whether_instrument,instrument_played,major_1,major_2,favorite_genre_1,favorite_genre_2,favorite_genre_3
0,4.0,no,nan,cognitive science,education sciences,pop,mandopop,r&b
1,5.0,yes,clarinet,data science,NaN,r&b,jazz,pop
2,0.5,yes,guitar,data science,economics,classical,country,jazz
3,2.0,yes,piano,bioengineering,mathematics,r&b,pop,folk
4,3.0,yes,piano,psychology,NaN,christian,pop,hiphop/rap

**Subset #2: Artist preference and major chice subset**

We will use this data set to see relation between music artist preference and major choice.

In [53]:
## ADD ' , ' TO BE ABLE TO SEPARATE ARTISTS INTO DIFFERNT COLUMNS 
survey['favorite_artist']=survey['favorite_artist'].replace('Kanye or Yung Lean','kanye, yung lean')
survey['favorite_artist']=survey['favorite_artist'].replace('Tyler, the Creator','tyler the creator')
survey['favorite_artist']=survey['favorite_artist'].replace('LE SSERAFIM 🧏\u200d♂️👆👉🙆\u200d♂️','le sserafim')


survey['favorite_artist']=survey['favorite_artist'].str.lower()
survey[['a1','a2','a3','a4','a5','a6','a7']] = survey['favorite_artist'].str.split(',', expand=True)

survey = survey.reindex(columns=['age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert','a1','a2','a3','a4','a5','a6','a7'])

In [54]:
##NEW DATAFRAME A1 FOR PEOPLE'S 1ST ARTIST LISTED
def standardize_a1 (str_a1):
    str_a1=str(str_a1)
    str_a1=str_a1.lower()
    str_a1=str_a1.strip()
    if 'specific' in str_a1 or 'none' in str_a1 or 'nan' in str_a1:
        output=np.nan
    else:
        output=str_a1
    return output
survey['a1']=survey['a1'].apply(standardize_a1)
survey_a1=survey.reindex(columns=['a1','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])
survey_a1=survey_a1.dropna(subset='a1')
survey_a1 = survey_a1.rename(columns={'a1':'artist_name'})

In [55]:
##NEW DATAFRAME A2 FOR PEOPLE'S 2ND ARTIST LISTED
def standardize_a2 (str_a2):
    str_a2=str(str_a2)
    str_a2=str_a2.lower()
    str_a2=str_a2.strip()
    if 'none' in str_a2 or 'nan' in str_a2:
        output=np.nan
    else:
        output=str_a2
    return output
survey['a2']=survey['a2'].apply(standardize_a2)
survey_a2=survey.reindex(columns=['a2','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])
survey_a2=survey_a2.dropna(subset='a2')
survey_a2 = survey_a2.rename(columns={'a2':'artist_name'})

In [56]:
##NEW DATAFRAME A3 FOR PEOPLE'S 3RD ARTIST LISTED
def standardize_a3 (str_a3):
    str_a3=str(str_a3)
    str_a3=str_a3.lower()
    str_a3=str_a3.strip()
    if 'none' in str_a3 or 'nan' in str_a3:
        output=np.nan
    elif 'é' in str_a3:
        output='beyonce'
    else:
        output=str_a3
    return output
survey['a3']=survey['a3'].apply(standardize_a3)
survey_a3=survey.reindex(columns=['a3','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])
survey_a3=survey_a3.dropna(subset='a3')
survey_a3 = survey_a3.rename(columns={'a3':'artist_name'})

In [57]:
##NEW DATAFRAME A4 FOR PEOPLE'S 4TH ARTIST LISTED
def standardize_a4 (str_a4):
    str_a4=str(str_a4)
    str_a4=str_a4.lower()
    str_a4=str_a4.strip()
    if 'ray' in str_a4:
        output='lana del rey'
    elif 'wising' in str_a4:
        output='wisin y yandel'
    elif 'none' in str_a4 or 'nan' in str_a4:
        output=np.nan
    else:
        output=str_a4
    return output
survey['a4']=survey['a4'].apply(standardize_a4)
survey_a4=survey.reindex(columns=['a4','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])
survey_a4=survey_a4.dropna(subset='a4')
survey_a4 = survey_a4.rename(columns={'a4':'artist_name'})

In [58]:
##NEW DATAFRAME A5 FOR PEOPLE'S 5TH ARTIST LISTED
def standardize_a5 (str_a5):
    str_a5=str(str_a5)
    str_a5=str_a5.lower()
    str_a5=str_a5.strip()
    if 'none' in str_a5 or 'nan' in str_a5:
        output=np.nan
    else:
        output=str_a5
    return output
survey['a5']=survey['a5'].apply(standardize_a5)
survey_a5=survey.reindex(columns=['a5','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])
survey_a5=survey_a5.dropna(subset='a5')
survey_a5 = survey_a5.rename(columns={'a5':'artist_name'})

In [59]:
##NEW DATAFRAME A6 FOR PEOPLE'S 6TH ARTIST LISTED
survey_a6=survey.reindex(columns=['a6','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])
survey_a6=survey_a6.dropna(subset='a6')
survey_a6 = survey_a6.rename(columns={'a6':'artist_name'})

In [60]:
##NEW DATAFRAME A6 FOR PEOPLE'S 7TH ARTIST LISTED
survey_a7=survey.reindex(columns=['a7','age', 'gender', 'state','country','major_1', 'major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','favorite_artist','listening_hours','whether_instrument','instrument_played','introvert_extrovert'])
survey_a7=survey_a7.dropna(subset='a7')
survey_a7 = survey_a7.rename(columns={'a7':'artist_name'})

In [61]:
##PUTTING THE DATAFRAMES TOGETHER

Because we have many different dataframes, we want to combine the individual survey results into one comprehensive dataset.

In [62]:
favorite_artist = pd.concat([survey_a1, survey_a2, survey_a3, survey_a4, survey_a5, survey_a6, survey_a7], ignore_index=True, axis=0)
favorite_artist = favorite_artist.reindex(columns=['artist_name','age','gender','major_1','major_2','favorite_genre_1','favorite_genre_2','favorite_genre_3','introvert_extrovert'])
favorite_artist.head()

,artist_name,age,gender,major_1,major_2,favorite_genre_1,favorite_genre_2,favorite_genre_3,introvert_extrovert
0,jonah kagen,21,female,cognitive science,education sciences,pop,mandopop,r&b,introvert
1,laufey,19,male,data science,NaN,r&b,jazz,pop,extrovert
2,laufey,20,female,bioengineering,mathematics,r&b,pop,folk,introvert
3,phil wickham,22,female,psychology,NaN,christian,pop,hiphop/rap,introvert
4,frank ocean,20,female,media,NaN,pop,folk,hiphop/rap,introvert

# Ethics & Privacy

The collection of students' music preferences paired with their majors involves handling personal information, which raises privacy concerns. Another potential issue is obtaining consent from students, where we need to guarantee that students will remain untraceable and anonymous, ensuring that responses cannot be traced back to individuals without their explicit permission. There is a risk of self-selection bias, where individuals who have a particular interest in music or strong opinions about their preferences may be more likely to respond. This could lead to an overrepresentation of certain preferences, which may not be reflective of the general student population at UCSD. Our approach to detecting specific biases before communicating our analysis includes a comprehensive evaluation of our data sources. Conducting this evaluation ensures that we're working with a dataset that's both diverse and free from inherent biases, setting a strong foundation for unbiased analysis. Throughout the analytical process, we’ll engage in ongoing validation efforts against varied data subsets and perform detailed sensitivity analyses. These efforts aim to understand how assumptions may influence our findings, helping us ensure our results are reflective of reality. Integrating this feedback into our work is essential for boosting the reliability of our analysis outcomes and demonstrating our commitment to maintaining high ethical standards.

To tackle identified issues, we will first conduct a root cause analysis, as previously mentioned, to understand the underlying problems and determine whether they stem from data quality, bias, or methodological flaws. Then, to address these challenges, we’ll use tactics that involve methodological adjustments and data remediation to ensure that our analysis is accurate. Additionally, using various methods beyond digital platforms, such as flyers, will help us reach a more diverse audience and address our concerns about bias. By being transparent with participants about how their data will be used and providing clear information on the purpose of the survey, we will help ensure that students' consent is informed and voluntary. Implementing these tactics will allow us to pinpoint more efficiently where issues stem from and facilitate our continuous improvement.

# Team Expectations

1. Equal Contribution: We expect each team member to contribute equally to all aspects of the project, including topic selection, data exploration, code writing, text writing, and editing. While recognizing individual strengths, we will ensure that workload is distributed evenly and that everyone participates in every part of the project.

2. Timely Communication and Accountability: We commit to regular communication throughout the quarter to discuss progress, address any issues or concerns, and ensure that deadlines are met. We will use imessage for group discussions and updates. If any member encounters difficulties or needs assistance, they will communicate this promptly to the team to find solutions together.

3. Respectful Conflict Resolution: In the event of conflicts or disagreements, we will engage in respectful dialogue and actively listen to each other's perspectives. We will address conflicts promptly and directly, striving to find mutually acceptable resolutions. If needed, we will seek guidance from the professor or teaching assistant to mediate conflicts.

4. Accountability for Non-Cooperative Behavior: If a team member fails to fulfill their responsibilities or contribute adequately to the project despite previous discussions and reminders, we will follow the procedure outlined in the team policies. This includes providing clear feedback to the non-cooperative member and escalating the issue to the professor if necessary, while maintaining professionalism and respect in all communications.

5. Continuous Improvement: Throughout the quarter, we will reflect on our teamwork dynamics and project progress, identifying areas for improvement and implementing strategies to enhance collaboration and productivity. We will utilize the end-of-quarter survey to provide constructive feedback and assess individual contributions, aiming for collective growth and success.

# Project Timeline Proposal



| Meeting Date | Meeting Time | Completed Before Meeting | Discuss at Meeting |
|---|---|---|---|
| 2/07 |  8 PM | N/A | Brainstorm ideas for hypothesis/research question; Section Distributions for Proposal | 
| 2/12 |  7 PM | Submit Project Proposal; Start background research on the topic and hypothesis | Discuss Team Expectations; Section Distributions for the Final Project; Work on the Google Form | 
| 2/16 | 8 AM  | Rough Draft of the Google Form  | Finalize hypothesis/research question; Check in on the progress of the Google form |
| 2/19 | 7 PM  | Search for other datasets; Finalize the Google Form | Discuss Checkpoint #1: Data; Work on Checkpoint #1; Discuss the release of Google Form; Discuss start of Final Report |
| 2/23 | 8 AM  | Release Google Form; Do more research into the topic; Get familiar with the data collected; Rough Draft of Checkpoint #1 | Check-in on progress; Discuss Checkpoint #1 |
| 2/26 | 7 PM  | Submit Checkpoint #1 [due 02/25]| Discuss data gathered by Google Form; Discuss Checkpoint #2; Discuss Final Report; Work on Data Section together |
| 3/01 | 8 AM  | Get familiar with data gathered so far | Check-in on progress; Discuss Checkpoint #2 |
| 3/04 | 7 PM  | Finish gathering dataset | Organize data; Discuss Checkpoint #2; Discuss Final Report|
| 3/08 | 8 AM  | Rough Draft of Checkpoint #2 | Check-in on progress |
| 3/11 | 7 PM  | Submit Checkpoint #2 [due 02/10]; Understand expectations of what’s needed for Final Report and Final Video | Discuss progress on the Final Report and Final Video; Outline the Final Report |
| 3/15 | 8 AM  | Rough Draft of Final Report | Check-in on progress; Discuss rough draft of Final Report, Discuss Final Video |
| 3/16-17 | [Not a meeting] | NA | Record Final Video |
| 3/18 | 7 PM (Subject to change due to Finals)  | Finalize Final Report and Final Video | Discuss finalized Final Report and Final Video |
| 3/19-20 | [Not a meeting] | NA | Record Final Video |
| 3/20 | Before 11:59 PM [Not a meeting] | NA | Submit the Final Report and Final Video |